name: fastyle_pricing_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  fastyle_dart: ^0.21.0

  fastyle_pricing:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


dependency_overrides:
  fastyle_dart: 
    path: /Users/thibaultzanini/Dev/tyrcord/fastyle_dart
