name: fastyle_pricing
description: A new Flutter package project.
version: 0.2.0-beta.3
homepage: https://github.com/tyrcord/fastyle_pricing

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fastyle_dart: ^0.22.0-beta.0

dev_dependencies:
  flutter_test:
    sdk: flutter
