name: fastyle_pricing
description: A new Flutter package project.
version: 0.3.0
homepage: https://github.com/tyrcord/fastyle_pricing

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  fastyle_dart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.10.1
