name: fastyle_pricing
description: A set of widgets with defined style.
version: 0.4.0
homepage: https://github.com/tyrcord/fastyle_pricing

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  fastyle_dart: ^0.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.15.2
